/**
 * @file error.h
 * @brief Error codes description
 *
 * @section License
 *
 * Copyright (C) 2010-2014 Oryx Embedded. All rights reserved.
 *
 * This program is free software; you can redistribute it and/or
 * modify it under the terms of the GNU General Public License
 * as published by the Free Software Foundation; either version 2
 * of the License, or (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program; if not, write to the Free Software Foundation,
 * Inc., 51 Franklin Street, Fifth Floor, Boston, MA  02110-1301, USA.
 *
 * @author Oryx Embedded (www.oryx-embedded.com)
 * @version 1.5.0
 **/

#ifndef _ERROR_H
#define _ERROR_H


/**
 * @brief Error codes
 **/

typedef enum
{
   __NO_ERROR = 0,                    ///<Success
   __ERROR_FAILURE = 1,               ///<Generic error code

   __ERROR_INVALID_PARAMETER,         ///<Invalid parameter
   __ERROR_PARAMETER_OUT_OF_RANGE,    ///<Specified parameter is out of range

   __ERROR_BAD_BLOCK,
   __ERROR_INVALID_RECIPIENT,         ///<Invalid recipient
   __ERROR_INVALID_INTERFACE,         ///<Invalid interface
   __ERROR_INVALID_ENDPOINT,          ///<Invalid endpoint
   __ERROR_INVALID_ALT_SETTING,       ///<Alternate setting does not exist
   __ERROR_UNSUPPORTED_REQUEST,       ///<Unsupported request
   __ERROR_UNSUPPORTED_CONFIGURATION, ///<Unsupported configuration
   __ERROR_UNSUPPORTED_FEATURE,       ///<Unsupported feature
   __ERROR_ENDPOINT_BUSY,             ///<Endpoint already in use
   __ERROR_USB_RESET,
   __ERROR_ABORTED,

   __ERROR_OUT_OF_MEMORY = 100,
   __ERROR_OUT_OF_RESOURCES,
   __ERROR_INVALID_REQUEST,
   __ERROR_NOT_IMPLEMENTED,
   __ERROR_VERSION_NOT_SUPPORTED,
   __ERROR_INVALID_SYNTAX,
   __ERROR_AUTHENTICATION_FAILED,
   __ERROR_UNEXPECTED_RESPONSE,
   __ERROR_UNEXPECTED_VALUE,

   __ERROR_OPEN_FAILED = 200,
   __ERROR_CONNECTION_FAILED,
   __ERROR_CONNECTION_CLOSING,
   __ERROR_CONNECTION_RESET,
   __ERROR_NOT_CONNECTED,
   __ERROR_ALREADY_CLOSED,
   __ERROR_ALREADY_CONNECTED,
   __ERROR_INVALID_SOCKET,
   __ERROR_PROTOCOL_UNREACHABLE,
   __ERROR_PORT_UNREACHABLE,
   __ERROR_INVALID_HEADER,
   __ERROR_WRONG_CHECKSUM,
   __ERROR_WRONG_IDENTIFIER,
   __ERROR_WRONG_CLIENT_ID,
   __ERROR_WRONG_SERVER_ID,
   __ERROR_NO_RESPONSE,
   __ERROR_RECEIVE_QUEUE_FULL,
   __ERROR_TIMEOUT,
   __ERROR_WOULD_BLOCK,
   __ERROR_INVALID_NAME,
   __ERROR_INVALID_OPTION,
   __ERROR_UNEXPECTED_STATE,
   __ERROR_INVALID_ADDRESS,
   __ERROR_INVALID_MESSAGE,
   __ERROR_INVALID_KEY,
   __ERROR_INVALID_KEY_LENGTH,
   __ERROR_INVALID_CHARACTER,
   __ERROR_INVALID_LENGTH,
   __ERROR_INVALID_PADDING,
   __ERROR_INVALID_MAC,
   __ERROR_INVALID_TAG,
   __ERROR_INVALID_TYPE,
   __ERROR_INVALID_CLASS,
   __ERROR_INVALID_VERSION,
   __ERROR_WRONG_LENGTH,
   __ERROR_WRONG_TYPE,
   __ERROR_WRONG_ENCODING,
   __ERROR_WRONG_VALUE,
   __ERROR_UNSUPPORTED_TYPE,
   __ERROR_UNSUPPORTED_CIPHER_SUITE,
   __ERROR_UNSUPPORTED_CIPHER_MODE,
   __ERROR_UNSUPPORTED_CIPHER_ALGO,
   __ERROR_UNSUPPORTED_KEY_EXCH_METHOD,
   __ERROR_UNSUPPORTED_SIGNATURE_ALGO,
   __ERROR_INVALID_SIGNATURE_ALGO,
   __ERROR_CERTIFICATE_REQUIRED,
   __ERROR_MESSAGE_TOO_LONG,
   __ERROR_OUT_OF_RANGE,
   __ERROR_MESSAGE_DISCARDED,

   __ERROR_INVALID_PACKET,
   __ERROR_BUFFER_EMPTY,
   __ERROR_BUFFER_OVERFLOW,

   __ERROR_INVALID_RESOURCE,
   __ERROR_INVALID_PATH,
   __ERROR_NOT_FOUND,
   __ERROR_ACCESS_DENIED,
   __ERROR_AUTH_REQUIRED,

   __ERROR_NO_RUNNING,

   __ERROR_INVALID_FILE = 300,
   __ERROR_FILE_NOT_FOUND,
   __ERROR_FILE_OPENING_FAILED,
   __ERROR_FILE_READING_FAILED,
   __ERROR_END_OF_FILE,
   __ERROR_UNEXPECTED_END_OF_FILE,
   __ERROR_UNKNOWN_FILE_FORMAT,

   __ERROR_INVALID_DIRECTORY,
   __ERROR_DIRECTORY_NOT_FOUND,

   __ERROR_FILE_SYSTEM_NOT_SUPPORTED = 400,
   __ERROR_UNKNOWN_FILE_SYSTEM,
   __ERROR_INVALID_FILE_SYSTEM,
   __ERROR_INVALID_BOOT_SECTOR_SIGNATURE,
   __ERROR_INVALID_SECTOR_SIZE,
   __ERROR_INVALID_CLUSTER_SIZE,
   __ERROR_INVALID_FILE_RECORD_SIZE,
   __ERROR_INVALID_INDEX_BUFFER_SIZE,
   __ERROR_INVALID_VOLUME_DESCRIPTOR_SIGNATURE,
   __ERROR_INVALID_VOLUME_DESCRIPTOR,
   __ERROR_INVALID_FILE_RECORD,
   __ERROR_INVALID_INDEX_BUFFER,
   __ERROR_INVALID_DATA_RUNS,
   __ERROR_WRONG_TAG_IDENTIFIER,
   __ERROR_WRONG_TAG_CHECKSUM,
   __ERROR_WRONG_MAGIC_NUMBER,
   __ERROR_WRONG_SEQUENCE_NUMBER,
   __ERROR_DESCRIPTOR_NOT_FOUND,
   __ERROR_ATTRIBUTE_NOT_FOUND,
   __ERROR_RESIDENT_ATTRIBUTE,
   __ERROR_NOT_RESIDENT_ATTRIBUTE,
   __ERROR_INVALID_SUPER_BLOCK,
   __ERROR_INVALID_SUPER_BLOCK_SIGNATURE,
   __ERROR_INVALID_BLOCK_SIZE,
   __ERROR_UNSUPPORTED_REVISION_LEVEL,
   __ERROR_INVALID_INODE_SIZE,
   __ERROR_INODE_NOT_FOUND,

   __ERROR_UNEXPECTED_MESSAGE = 500,

   __ERROR_URL_TOO_LONG,
   __ERROR_QUERY_STRING_TOO_LONG,

   __ERROR_NO_ADDRESS,
   __ERROR_NO_BINDING,
   __ERROR_NOT_ON_LINK,
   __ERROR_USE_MULTICAST,
   __ERROR_NAK_RECEIVED,

   __ERROR_INVALID_LEVEL,
   __ERROR_WRONG_STATE,
   __ERROR_END_OF_STREAM,
   __ERROR_LINK_DOWN,
   __ERROR_INVALID_OPTION_LENGTH,
   __ERROR_IN_PROGRESS,

   __ERROR_NO_ACK,
   __ERROR_INVALID_METADATA,
   __ERROR_NOT_CONFIGURED,
   __ERROR_NAME_RESOLUTION_FAILED,
   __ERROR_NO_ROUTE,

   __ERROR_WRITE_FAILED,
   __ERROR_READ_FAILED,
   __ERROR_UPLOAD_FAILED,

   __ERROR_INVALID_SIGNATURE,

   __ERROR_BAD_RECORD_MAC,
   __ERROR_RECORD_OVERFLOW,
   __ERROR_HANDSHAKE_FAILED,
   __ERROR_NO_CERTIFICATE,
   __ERROR_BAD_CERTIFICATE,
   __ERROR_UNSUPPORTED_CERTIFICATE,
   __ERROR_CERTIFICATE_EXPIRED,
   __ERROR_UNKNOWN_CA,
   __ERROR_DECODING_FAILED,
   __ERROR_DECRYPTION_FAILED,
   __ERROR_ILLEGAL_PARAMETER,
   __ERROR_UNSUPPORTED_EXTENSION,

   __ERROR_MORE_DATA_REQUIRED,
   __ERROR_TLS_NOT_SUPPORTED,
   __ERROR_PRNG_NOT_READY,
   __ERROR_SERVICE_CLOSING,
   __ERROR_INVALID_TIMESTAMP,
   __ERROR_NO_DNS_SERVER,

   __ERROR_OBJECT_NOT_FOUND,
   __ERROR_INSTANCE_NOT_FOUND,

   __ERROR_NO_MATCH,
   __ERROR_PARTIAL_MATCH
} error_t;

#endif
